sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: ChmWTLjsfB1lbOk0TIRqidjjAbHme8IoSGoQdMbHLgfFYCVXMosP/BhxhS8EulbuqnBlEqKVNHGtwfpbuEVUxxJwiGUZtFjjeQniZrArx5Xc72opqwTv2npv0xXH/r3QzG6wxD+Zh9z6j7OEvPgcdAFEQNJq281y7jiHZ6RR4lYGCAXzE+EvGReThn0gAiG7FfRoqzSFEuaF5Jo1Lk0FmBFfMw+bALkuuUuAoSPmRZDl1ZqliWJ/Tgy45iMBZIQoM3ZExBqcZpjLG1UA8OIlqTjKOK5Ir/QBeYnftjtB5YfQzQdrH2pIKMhQqtLy2R38UWORQA60C/zYxdabbN4qQo7dzA7u3DKenCZpx8V+TfcN5qNTgCTIyK9HvQsHWifBXIistAxhQVfpbGjUn7luHglni3W4wCBQqKEz1CbRCd5BxLZmekgRC90iNPliDrHUbUTIVH0BUrQZGCPTix1qcZuYgy+3l+DLwM3ShN67pAJ4oN1PppBVvb0PJNy6RI6O8Q1QGC/th8rR5qz5cZOROL0y6WKuCDMdz/PS91ojvy4c2tTgLvlTPe7FOxqu2v5F5+86G/qVW1WnV4cRG1urAo1wyPnIMjvOLuVKW/b2uHYtfgKYxapqL9mTL9/hZATSIBMzfga1T1iEF8qJshk+SSz0WZh5Gt4WXKBr8WPxVCQ=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: Y4fsRe15aim+VWuZ1NAhkVO6OpAFRu5JOmKLFCOiiz0Hltpr/sxJ9YGVJzNnatbg4xrOuu7rDd7tDKKJQLmOjSrz7FT2wHzNZAK7X4odCxWbnxQBE+jBieuxGh6F8hLQBL0Wd3575FsI5xMcFX/ERkITDuVGtuyhmYO8d75wYKaBZQlO5NaleLO4LbUHAqrfM0y4T5WUrQEukwBwUJF0yG8H8XGX0Bf3AhkLF+2oTZ8fX1Y7vuiFX/jtyuGBN7iLamUTqjB4t+QedLigZWTjd87qPsGz0XFoQUGiDG1GIcXnLuziPfAI/AO4VcAaUioUUu1CHGgvXZG97dBqhec083Q+i/EivYwnaL9cDj8VhNWKBiFoaKx6dPyf6cgEYUXWxzQoxeilCIauCgaN+X8Pl33isn9z4Bami2f086VQWGh9zgmwxKDM3RD2AZTKS9esTn+PJJs0SVUPTZAhF/4+GTfqno88twPg3+8SXMpXZwSn9rZTFU/U007avr8pj8mpgHrCQ1T4zVUueUJR3vXLRj86S1OSNwegQk1+k5Miwrlvg/pPM/nGF/kHShnWmC2OdP2xxN0pq1JUwhoqmaTvTJB4c4tbtU7FJspQSVVxhKopqCLklnJSsCRFBI1HiLPvJnfl4UFeGeC7fldil1znFb6ojv5azKEcATOzA+M2NzE=
